name: Xây Dựng Generic System Image

on:
  watch:
    types: [started]
    
env:
  ROM_URL: https://doc-10-8o-docs.googleusercontent.com/docs/securesc/s76dsd0r0kl9usov2evfod3spoes3tli/05jung4o6s4rfh51du1qrdntjq8be15b/1604385900000/05436494942329401109/05436494942329401109/12bXG-RuEcUTFTZgDk57M8ChZPyxuDGT9?e=download&authuser=0&nonce=j0qvg22s0i4a6&user=05436494942329401109&hash=dtnn964tgnt2tep5is6hhg76sr4p32g4
  ROM_NAME: MIUI
  BUILD_AB: true
  BUILD_Aonly: false
  ROM_AONLY: Miui_RM8.7z
  ROM_AB: Miui_RM8.7z

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
       - name: Kiểm Tra Trích Xuất
         uses: actions/checkout@master
       
       - name: Dọn Dẹp Đầy Đủ
         run: |
           docker rmi `docker images -q`
           sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d
           sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php*
           sudo -E apt-get update
           sudo -E apt-get -y autoremove --purge
           sudo -E apt-get clean 
           
       - name: Thiết Lập Môi Trường 
         run: |
            sudo -E apt-get -qq update
            sudo -E apt-get -qq install git openjdk-8-jdk p7zip
       
       - name: Lấy Nguồn 
         run: git clone --recurse-submodules https://github.com/erfanoabdi/ErfanGSIs.git
       
       - name: Thiết lập các yêu cầu 
         run: |
              sudo chmod -R 777 ErfanGSIs
              cd ErfanGSIs
              sudo bash setup.sh
       
       - name: Tải Xuống ROM - Khởi Tạo Aonly GSI
         if: env.BUILD_AONLY == 'true'
         run: sudo ./ErfanGSIs/url2GSI.sh -a $ROM_URL $ROM_NAME
       
       - name: 7z Aonly GSI
         if: env.BUILD_AONLY == 'true'
         run: 7za a -t7z -r $ROM_AONLY ErfanGSIs/output/*
       
       - name: Upload Aonly
         if: env.BUILD_AONLY == 'true'
         run: |
              curl -sL https://git.io/file-transfer | sh
              ./transfer bit $ROM_AONLY
           
       - name: Dọn Dẹp Đầu Ra
         if: env.BUILD_AB == 'true'
         run: sudo rm -rf ErfanGSIs/output/*
         
       - name: Tải Xuống ROM - Khởi Tạo AB GSI
         if: env.BUILD_AB == 'true'
         run: sudo ./ErfanGSIs/url2GSI.sh -b $ROM_URL $ROM_NAME

       - name: 7z AB GSI
         if: env.BUILD_AB == 'true'
         run: 7za a -t7z -r $ROM_AB ErfanGSIs/output/*

       - name: Upload AB 
         if: env.BUILD_AB == 'true'
         run: |
              curl -sL https://git.io/file-transfer | sh
              ./transfer bit $ROM_AB
              
           
